name:        {{cookiecutter.package_name}}
version:     0.0.0

{%- if cookiecutter.github_username != '' and cookiecutter.github_repo_name != '' %}
description:  Please see the README on GitHub at <https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.github_repo_name}}#readme>
homepage:     https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.github_repo_name}}#readme
bug-reports:  https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.github_repo_name}}/issues

{% endif %}
{%- if cookiecutter.author_name != '' %}
author:       {{cookiecutter.author_name}}
copyright:    2020 {{cookiecutter.author_name}}

{% endif %}
license:      AGPL-3.0-only
license-file: LICENSE

build-type:   Simple

extra-source-files:
  - README.md
  - CHANGELOG.md

# Informed by Max Tagher's 'Enable All the Warnings' blog post
#
# https://medium.com/mercury-bank/enable-all-the-warnings-a0517bc081c3
ghc-options:
  - -fwarn-tabs
  - -fhide-source-paths
  - -fprint-potential-instances
  - -optP-Wno-nonportable-include-path
  - -Wall
  - -Wcpp-undef
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wno-unused-do-bind
  - -Wno-deprecations
  - -Wno-monomorphism-restriction
  - -Wno-unticked-promoted-constructors
  - -Wpartial-fields
  - -Wredundant-constraints

# These extensions should _always_ be enabled...
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - ScopedTypeVariables

# Dependencies common to all modules
dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: library
  dependencies: []

executables:
  {{cookiecutter.package_name}}-exe:
    main: Main.hs
    source-dirs: executables
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    # The only dependency required to build the executable is the library
    dependencies: {{cookiecutter.package_name}}

tests:
  {{cookiecutter.package_name}}-tests:
    main: Driver.hs
    source-dirs: tests
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies: 
      # Project code under test
      - {{cookiecutter.package_name}}

      # External libraries required _only_ for testing
      - hedgehog
      - hedgehog-quickcheck
      - QuickCheck
      - tasty
      - tasty-discover
      - tasty-hedgehog
      - tasty-hspec
      - tasty-quickcheck

  readme-test:
    main: Documentation.lhs
    source-dirs: documentation
    build-tools: markdown-unlit
    ghc-options: "-pgmL markdown-unlit"
